name: Ping Supabase Database

on:
  schedule:
    - cron: "0 */2 * * *" # This will run every 2 hours
  worflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase database
        run: |
          curl -X POST https://wzsxahnbjeixwlrpwzcd.supabase.co/rest/v1/rpc/ping \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
          -H "Content-Type: application/json"
