name: Ping Supabase Database

on:
  schedule:
    - cron: "0 */2 * * *" # This will run every 2 hours
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase database
        run: |
          curl -v -X POST 'https://wzsxahnbjeixwlrpwzcd.supabase.co/rest/v1/rpc/ping' \
          -H "Content-Type: application/json" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
